<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <link rel="stylesheet" href="<?php echo $this->css?>" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
</head>

<body>
<script type="importmap">
{
    "imports": {
            "vue": /js/libs/vue/min.js"
    }
}
</script>
<div id="wpBody" class="schedule tab_content current">
    <ul class="tabs">
        <li v-for="{ day, index } in cleanSchedule" :class="{ 'active': index === currentTab.value }">
            <div @click="currentTab = index">
                {{day.dayOfWeek}}<span>{{day.dayOfMonth}}</span>
            </div>
        </li>
    </ul>

    <div class="schedule_content">
        <div v-for="{ day, index } in cleanSchedule" id="day-{{dayOfMonth}}" :class="[ 'active': index === currentTab.value, schedule_item ]">
            <div v-if="day.shows.length == 0" class="row empty-schedule">
                <?php echo _('Looks like there are no shows scheduled on this day.') ?>
            </div>
            <div v-else v-for="show in day" class="row">
                <div class="time_grid">{{show.show_start_hour}} - {{show.show_end_hour}}</div>
                <div class="name_grid">{{{show.name}}}</div>
            </div>
        </div>
    </div>

    <div class="weekly-schedule-widget-footer" <?php if ($this->widgetStyle == "premium") echo "style='display:none'"; ?>>
        <a href="<?php echo PRODUCT_SITE_URL; ?>" target="_blank"><?php printf(_('Powered by %s'), PRODUCT_NAME); ?></a>
    </div>
</div>

<script type="module">
    import { createApp } from 'vue'

    createApp({
        setup() {
            // Pull in scheduling data
            const importSchedule = <?php echo $this->schedule_data; ?>;  // Object prepared in JSON, w/o API call
            const cleanSchedule = []

            // Insert shows into correct locations in importShows array (work-around for API v.1)
            let importShows = importSchedule["shows"];
            importShows.forEach(element => {
                // Convert timestamps to JS (sec -> millisec)
                var start_date = new Date(element.starts_timestamp*1000);
                var end_date = new Date(element.ends_timestamp*1000);
                // Check date of show so we know where to assign it to
                var format_start_date = start_date.getFullYear() + "-" + (start_date.getMonth()+1) + "-" + start_date.getDate();
                // Assign show to correct location
                if (importSchedule["weekDays"][format_start_date] !== undefined) {
                    importSchedule["weekDays"][format_start_date]["shows"].push(
                        {
                            "show_start_hour": start_date.toLocaleTimeString([], { hour: 'numeric', minute : 'numeric' }),
                            "show_end_hour": end_date.toLocaleTimeString([], { hour: 'numeric', minute : 'numeric' }),
                            "name": element.name
                        }
                    );
                }
            });

            for (var i = 0; i <= 6; i++) {
                cleanSchedule.push(Object.values(importSchedule.weekDays)[i]);
            }

            const currentTab = ref(0)

            return {
                cleanSchedule,
                currentTab,
            };
        }
    }).mount('#wpBody');
</script>
</body>
</html>
